### ISSUE TITLE
Add vendor folder to gitignore and add proper build instructions

### ISSUE THREAD

**Issue by kousiksatish** [Spockuto/Remote-Print#2]
Check out https://github.com/kousiksatish/photograhy-contest-pragyan for reference. Right now I am not able to run it on my system. It says some file not found error. It is better that we clone and do a composer install to get the vendor files.

**Comment by suhithr** [comment]
As a temporary fix, delete the `vendor/` folder. Then run `composer install`.
Generate a key with `php artisan key:generate` and create a `.env` file with the default contents.

After this it should work.
